# 📊 Data Profiling — Team Outliers

**Mục tiêu**: Kiểm tra tổng quan 15 file dữ liệu, phát hiện giá trị thiếu (null), kiểu dữ liệu và các vấn đề bất thường.

In [ ]:
import polars as pl
import sys
from pathlib import Path
from IPython.display import display

# Add src to path to import DataLoader
sys.path.append(str(Path("..").resolve()))
from src.data_loader import DataLoader

loader = DataLoader()
all_dfs = loader.load_all()

✅ Loaded customers: 121,930 rows
✅ Loaded geography: 39,948 rows
✅ Loaded inventory: 60,247 rows
✅ Loaded order_items: 714,669 rows
✅ Loaded orders: 646,945 rows
✅ Loaded payments: 646,945 rows
✅ Loaded products: 2,412 rows
✅ Loaded promotions: 50 rows
✅ Loaded returns: 39,939 rows
✅ Loaded reviews: 113,551 rows
✅ Loaded sales: 3,833 rows
✅ Loaded sample_submission: 548 rows
✅ Loaded shipments: 566,067 rows
✅ Loaded web_traffic: 3,652 rows

## 1. Kiểm tra số lượng dòng và cột

In [ ]:
summary = []
for name, df in all_dfs.items():
    summary.append({
        "Table": name,
        "Rows": len(df),
        "Columns": len(df.columns),
        "Size (MB)": round(df.estimated_size() / (1024 * 1024), 2)
    })

pl.DataFrame(summary).sort("Rows", descending=True)

shape: (14, 4)
┌───────────────────┬────────┬─────────┬───────────┐
│ Table             ┆ Rows   ┆ Columns ┆ Size (MB) │
│ ---               ┆ ---    ┆ ---     ┆ ---       │
│ str               ┆ i64    ┆ i64     ┆ f64       │
╞═══════════════════╪════════╪═════════╪═══════════╡
│ order_items       ┆ 714669 ┆ 7       ┆ 29.9      │
│ orders            ┆ 646945 ┆ 8       ┆ 39.38     │
│ payments          ┆ 646945 ┆ 4       ┆ 20.33     │
│ shipments         ┆ 566067 ┆ 4       ┆ 12.96     │
│ customers         ┆ 121930 ┆ 7       ┆ 5.79      │
│ …                 ┆ …      ┆ …       ┆ …         │
│ sales             ┆ 3833   ┆ 3       ┆ 0.07      │
│ web_traffic       ┆ 3652   ┆ 7       ┆ 0.19      │
│ products          ┆ 2412   ┆ 8       ┆ 0.14      │
│ sample_submission ┆ 548    ┆ 3       ┆ 0.01      │
│ promotions        ┆ 50     ┆ 10      ┆ 0.0       │
└───────────────────┴────────┴─────────┴───────────┘

## 2. Kiểm tra giá trị Null

In [ ]:
def check_nulls(name, df):
    null_counts = df.null_count()
    null_pct = (null_counts / len(df) * 100)
    return null_pct

for name, df in all_dfs.items():
    nulls = check_nulls(name, df)
    if nulls.sum_horizontal()[0] > 0:
        print(f"\n⚠️ {name} has null values:")
        # Filter columns with nulls > 0
        for col in df.columns:
            pct = nulls[col][0]
            if pct > 0:
                print(f"  - {col}: {pct:.2f}%")

⚠️ order_items has null values:
  - promo_id: 61.34%
  - promo_id_2: 99.97%

⚠️ promotions has null values:
  - applicable_category: 80.00%

## 3. Kiểu dữ liệu

In [ ]:
for name, df in all_dfs.items():
    print(f"\n--- {name} ---")
    print(df.schema)

--- customers ---
Schema({'customer_id': Int64, 'zip': Int64, 'city': String, 'signup_date': Date, 'gender': String, 'age_group': String, 'acquisition_channel': String})

--- geography ---
Schema({'zip': Int64, 'city': String, 'region': String, 'district': String})

--- inventory ---
Schema({'snapshot_date': Date, 'product_id': Int64, 'stock_on_hand': Int64, 'units_received': Int64, 'units_sold': Int64, 'stockout_days': Int64, 'days_of_supply': Float64, 'fill_rate': Float64, 'stockout_flag': Int64, 'overstock_flag': Int64, 'reorder_flag': Int64, 'sell_through_rate': Float64, 'product_name': String, 'category': String, 'segment': String, 'year': Int64, 'month': Int64})

--- order_items ---
Schema({'order_id': Int64, 'product_id': Int64, 'quantity': Int64, 'unit_price': Float64, 'discount_amount': Float64, 'promo_id': String, 'promo_id_2': String})

--- orders ---
Schema({'order_id': Int64, 'order_date': Date, 'customer_id': Int64, 'zip': Int64, 'order_status': String, 'payment_method': String, 'device_type': String, 'order_source': String})

--- payments ---
Schema({'order_id': Int64, 'payment_method': String, 'payment_value': Float64, 'installments': Int64})

--- products ---
Schema({'product_id': Int64, 'product_name': String, 'category': String, 'segment': String, 'size': String, 'color': String, 'price': Float64, 'cogs': Float64})

--- promotions ---
Schema({'promo_id': String, 'promo_name': String, 'promo_type': String, 'discount_value': Float64, 'start_date': String, 'end_date': String, 'applicable_category': String, 'promo_channel': String, 'stackable_flag': Int64, 'min_order_value': Int64})

--- returns ---
Schema({'return_id': String, 'order_id': Int64, 'product_id': Int64, 'return_date': String, 'return_reason': String, 'return_quantity': Int64, 'refund_amount': Float64})

--- reviews ---
Schema({'review_id': String, 'order_id': Int64, 'product_id': Int64, 'customer_id': Int64, 'review_date': String, 'rating': Int64, 'review_title': String})

--- sales ---
Schema({'Date': Date, 'Revenue': Float64, 'COGS': Float64})

--- sample_submission ---
Schema({'Date': String, 'Revenue': Float64, 'COGS': Float64})

--- shipments ---
Schema({'order_id': Int64, 'ship_date': Date, 'delivery_date': Date, 'shipping_fee': Float64})

--- web_traffic ---
Schema({'date': Date, 'sessions': Int64, 'unique_visitors': Int64, 'page_views': Int64, 'bounce_rate': Float64, 'avg_session_duration_sec': Float64, 'traffic_source': String})

## 4. Phân bố và thống kê

In [ ]:
for name, df in all_dfs.items():
    print(f"\n--- {name} ---")
    num_cols = [col for col, dtype in df.schema.items() if dtype in pl.NUMERIC_DTYPES]
    if num_cols:
        display(df.select(num_cols).describe())
    else:
        print("No numerical columns")

--- customers ---

C:\Users\Admin\AppData\Local\Temp\ipykernel_26392\3365962957.py:3: DeprecationWarning: `NUMERIC_DTYPES` was deprecated in version 1.0.0. Define your own data type groups or use the `polars.selectors` module for selecting columns of a certain data type.
  num_cols = [col for col, dtype in df.schema.items() if dtype in pl.NUMERIC_DTYPES]

shape: (9, 3)
┌────────────┬──────────────┬──────────────┐
│ statistic  ┆ customer_id  ┆ zip          │
│ ---        ┆ ---          ┆ ---          │
│ str        ┆ f64          ┆ f64          │
╞════════════╪══════════════╪══════════════╡
│ count      ┆ 121930.0     ┆ 121930.0     │
│ null_count ┆ 0.0          ┆ 0.0          │
│ mean       ┆ 78736.898663 ┆ 50990.165595 │
│ std        ┆ 45492.202886 ┆ 26871.914605 │
│ min        ┆ 1.0          ┆ 1001.0       │
│ 25%        ┆ 39343.0      ┆ 28689.0      │
│ 50%        ┆ 78785.0      ┆ 49835.0      │
│ 75%        ┆ 118157.0     ┆ 73488.0      │
│ max        ┆ 157563.0     ┆ 99950.0      │
└────────────┴──────────────┴──────────────┘

--- geography ---

shape: (9, 2)
┌────────────┬──────────────┐
│ statistic  ┆ zip          │
│ ---        ┆ ---          │
│ str        ┆ f64          │
╞════════════╪══════════════╡
│ count      ┆ 39948.0      │
│ null_count ┆ 0.0          │
│ mean       ┆ 50895.084735 │
│ std        ┆ 27042.257341 │
│ min        ┆ 1.0          │
│ 25%        ┆ 28280.0      │
│ 50%        ┆ 49877.0      │
│ 75%        ┆ 73526.0      │
│ max        ┆ 99950.0      │
└────────────┴──────────────┘

--- inventory ---

shape: (9, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ product_i ┆ stock_on_ ┆ units_rec ┆ … ┆ reorder_f ┆ sell_thro ┆ year      ┆ month    │
│ ---       ┆ d         ┆ hand      ┆ eived     ┆   ┆ lag       ┆ ugh_rate  ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ f64      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 60247.0   ┆ 60247.0   ┆ 60247.0   ┆ … ┆ 60247.0   ┆ 60247.0   ┆ 60247.0   ┆ 60247.0  │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 1311.4084 ┆ 189.29845 ┆ 18.046807 ┆ … ┆ 0.0       ┆ 0.152275  ┆ 2017.2227 ┆ 6.617292 │
│           ┆ 68        ┆ 5         ┆           ┆   ┆           ┆           ┆ 99        ┆          │
│ std       ┆ 673.05176 ┆ 316.97612 ┆ 34.080228 ┆ … ┆ 0.0       ┆ 0.139291  ┆ 2.972353  ┆ 3.385629 │
│           ┆ 9         ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 1.0       ┆ 3.0       ┆ 1.0       ┆ … ┆ 0.0       ┆ 0.0004    ┆ 2012.0    ┆ 1.0      │
│ 25%       ┆ 760.0     ┆ 15.0      ┆ 2.0       ┆ … ┆ 0.0       ┆ 0.0421    ┆ 2015.0    ┆ 4.0      │
│ 50%       ┆ 1223.0    ┆ 62.0      ┆ 6.0       ┆ … ┆ 0.0       ┆ 0.1111    ┆ 2017.0    ┆ 7.0      │
│ 75%       ┆ 1942.0    ┆ 210.0     ┆ 19.0      ┆ … ┆ 0.0       ┆ 0.2381    ┆ 2020.0    ┆ 10.0     │
│ max       ┆ 2412.0    ┆ 2673.0    ┆ 817.0     ┆ … ┆ 0.0       ┆ 0.8531    ┆ 2022.0    ┆ 12.0     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

--- order_items ---

shape: (9, 6)
┌────────────┬───────────────┬────────────┬──────────┬─────────────┬─────────────────┐
│ statistic  ┆ order_id      ┆ product_id ┆ quantity ┆ unit_price  ┆ discount_amount │
│ ---        ┆ ---           ┆ ---        ┆ ---      ┆ ---         ┆ ---             │
│ str        ┆ f64           ┆ f64        ┆ f64      ┆ f64         ┆ f64             │
╞════════════╪═══════════════╪════════════╪══════════╪═════════════╪═════════════════╡
│ count      ┆ 714669.0      ┆ 714669.0   ┆ 714669.0 ┆ 714669.0    ┆ 714669.0        │
│ null_count ┆ 0.0           ┆ 0.0        ┆ 0.0      ┆ 0.0         ┆ 0.0             │
│ mean       ┆ 411615.076561 ┆ 1234.93137 ┆ 4.495988 ┆ 5114.690157 ┆ 1048.887415     │
│ std        ┆ 240480.310686 ┆ 691.332564 ┆ 2.290143 ┆ 3774.817912 ┆ 2280.530606     │
│ min        ┆ 1.0           ┆ 1.0        ┆ 1.0      ┆ 392.57      ┆ 0.0             │
│ 25%        ┆ 203229.0      ┆ 689.0      ┆ 2.0      ┆ 1906.89     ┆ 0.0             │
│ 50%        ┆ 409306.0      ┆ 990.0      ┆ 4.0      ┆ 4257.77     ┆ 0.0             │
│ 75%        ┆ 618981.0      ┆ 2045.0     ┆ 6.0      ┆ 7273.76     ┆ 967.63          │
│ max        ┆ 834397.0      ┆ 2412.0     ┆ 8.0      ┆ 43056.0     ┆ 35235.47        │
└────────────┴───────────────┴────────────┴──────────┴─────────────┴─────────────────┘

--- orders ---

shape: (9, 4)
┌────────────┬───────────────┬──────────────┬──────────────┐
│ statistic  ┆ order_id      ┆ customer_id  ┆ zip          │
│ ---        ┆ ---           ┆ ---          ┆ ---          │
│ str        ┆ f64           ┆ f64          ┆ f64          │
╞════════════╪═══════════════╪══════════════╪══════════════╡
│ count      ┆ 646945.0      ┆ 646945.0     ┆ 646945.0     │
│ null_count ┆ 0.0           ┆ 0.0          ┆ 0.0          │
│ mean       ┆ 417189.470332 ┆ 84906.203535 ┆ 55410.740423 │
│ std        ┆ 240785.704463 ┆ 48446.922752 ┆ 28876.471824 │
│ min        ┆ 1.0           ┆ 1.0          ┆ 1001.0       │
│ 25%        ┆ 208728.0      ┆ 41336.0      ┆ 30904.0      │
│ 50%        ┆ 417211.0      ┆ 87279.0      ┆ 54129.0      │
│ 75%        ┆ 625628.0      ┆ 133282.0     ┆ 83301.0      │
│ max        ┆ 834397.0      ┆ 157563.0     ┆ 99950.0      │
└────────────┴───────────────┴──────────────┴──────────────┘

--- payments ---

shape: (9, 4)
┌────────────┬───────────────┬───────────────┬──────────────┐
│ statistic  ┆ order_id      ┆ payment_value ┆ installments │
│ ---        ┆ ---           ┆ ---           ┆ ---          │
│ str        ┆ f64           ┆ f64           ┆ f64          │
╞════════════╪═══════════════╪═══════════════╪══════════════╡
│ count      ┆ 646945.0      ┆ 646945.0      ┆ 646945.0     │
│ null_count ┆ 0.0           ┆ 0.0           ┆ 0.0          │
│ mean       ┆ 417189.470332 ┆ 24238.334426  ┆ 3.448319     │
│ std        ┆ 240785.704463 ┆ 22378.475324  ┆ 3.119582     │
│ min        ┆ 1.0           ┆ 389.74        ┆ 1.0          │
│ 25%        ┆ 208728.0      ┆ 7681.06       ┆ 1.0          │
│ 50%        ┆ 417211.0      ┆ 17229.44      ┆ 3.0          │
│ 75%        ┆ 625628.0      ┆ 33706.35      ┆ 6.0          │
│ max        ┆ 834397.0      ┆ 331570.4      ┆ 12.0         │
└────────────┴───────────────┴───────────────┴──────────────┘

--- products ---

shape: (9, 4)
┌────────────┬────────────┬─────────────┬─────────────┐
│ statistic  ┆ product_id ┆ price       ┆ cogs        │
│ ---        ┆ ---        ┆ ---         ┆ ---         │
│ str        ┆ f64        ┆ f64         ┆ f64         │
╞════════════╪════════════╪═════════════╪═════════════╡
│ count      ┆ 2412.0     ┆ 2412.0      ┆ 2412.0      │
│ null_count ┆ 0.0        ┆ 0.0         ┆ 0.0         │
│ mean       ┆ 1206.5     ┆ 4928.216231 ┆ 3868.346732 │
│ std        ┆ 696.428747 ┆ 4776.737669 ┆ 3878.584151 │
│ min        ┆ 1.0        ┆ 9.056594    ┆ 5.183829    │
│ 25%        ┆ 604.0      ┆ 59.516852   ┆ 35.103127   │
│ 50%        ┆ 1207.0     ┆ 4400.34     ┆ 3188.954802 │
│ 75%        ┆ 1809.0     ┆ 7714.35     ┆ 5863.69483  │
│ max        ┆ 2412.0     ┆ 40950.0     ┆ 38902.5     │
└────────────┴────────────┴─────────────┴─────────────┘

--- promotions ---

shape: (9, 4)
┌────────────┬────────────────┬────────────────┬─────────────────┐
│ statistic  ┆ discount_value ┆ stackable_flag ┆ min_order_value │
│ ---        ┆ ---            ┆ ---            ┆ ---             │
│ str        ┆ f64            ┆ f64            ┆ f64             │
╞════════════╪════════════════╪════════════════╪═════════════════╡
│ count      ┆ 50.0           ┆ 50.0           ┆ 50.0            │
│ null_count ┆ 0.0            ┆ 0.0            ┆ 0.0             │
│ mean       ┆ 18.5           ┆ 0.24           ┆ 46000.0         │
│ std        ┆ 11.241777      ┆ 0.431419       ┆ 66116.779802    │
│ min        ┆ 10.0           ┆ 0.0            ┆ 0.0             │
│ 25%        ┆ 12.0           ┆ 0.0            ┆ 0.0             │
│ 50%        ┆ 18.0           ┆ 0.0            ┆ 0.0             │
│ 75%        ┆ 20.0           ┆ 0.0            ┆ 100000.0        │
│ max        ┆ 50.0           ┆ 1.0            ┆ 200000.0        │
└────────────┴────────────────┴────────────────┴─────────────────┘

--- returns ---

shape: (9, 5)
┌────────────┬───────────────┬────────────┬─────────────────┬───────────────┐
│ statistic  ┆ order_id      ┆ product_id ┆ return_quantity ┆ refund_amount │
│ ---        ┆ ---           ┆ ---        ┆ ---             ┆ ---           │
│ str        ┆ f64           ┆ f64        ┆ f64             ┆ f64           │
╞════════════╪═══════════════╪════════════╪═════════════════╪═══════════════╡
│ count      ┆ 39939.0       ┆ 39939.0    ┆ 39939.0         ┆ 39939.0       │
│ null_count ┆ 0.0           ┆ 0.0        ┆ 0.0             ┆ 0.0           │
│ mean       ┆ 409061.984176 ┆ 1244.23273 ┆ 2.743834        ┆ 12784.458964  │
│ std        ┆ 240063.904576 ┆ 691.747822 ┆ 1.82826         ┆ 14092.150154  │
│ min        ┆ 2.0           ┆ 3.0        ┆ 1.0             ┆ 458.81        │
│ 25%        ┆ 202660.0      ┆ 702.0      ┆ 1.0             ┆ 3573.46       │
│ 50%        ┆ 404254.0      ┆ 992.0      ┆ 2.0             ┆ 7888.88       │
│ 75%        ┆ 615623.0      ┆ 2049.0     ┆ 4.0             ┆ 16882.09      │
│ max        ┆ 833351.0      ┆ 2412.0     ┆ 8.0             ┆ 160937.94     │
└────────────┴───────────────┴────────────┴─────────────────┴───────────────┘

--- reviews ---

shape: (9, 5)
┌────────────┬───────────────┬─────────────┬──────────────┬──────────┐
│ statistic  ┆ order_id      ┆ product_id  ┆ customer_id  ┆ rating   │
│ ---        ┆ ---           ┆ ---         ┆ ---          ┆ ---      │
│ str        ┆ f64           ┆ f64         ┆ f64          ┆ f64      │
╞════════════╪═══════════════╪═════════════╪══════════════╪══════════╡
│ count      ┆ 113551.0      ┆ 113551.0    ┆ 113551.0     ┆ 113551.0 │
│ null_count ┆ 0.0           ┆ 0.0         ┆ 0.0          ┆ 0.0      │
│ mean       ┆ 408999.51974  ┆ 1232.018705 ┆ 85694.342762 ┆ 3.936011 │
│ std        ┆ 239021.922809 ┆ 690.839232  ┆ 48501.480918 ┆ 1.149867 │
│ min        ┆ 1.0           ┆ 3.0         ┆ 2.0          ┆ 1.0      │
│ 25%        ┆ 202049.0      ┆ 689.0       ┆ 42097.0      ┆ 3.0      │
│ 50%        ┆ 406841.0      ┆ 981.0       ┆ 89755.0      ┆ 4.0      │
│ 75%        ┆ 614845.0      ┆ 2045.0      ┆ 133850.0     ┆ 5.0      │
│ max        ┆ 833296.0      ┆ 2412.0      ┆ 157563.0     ┆ 5.0      │
└────────────┴───────────────┴─────────────┴──────────────┴──────────┘

--- sales ---

shape: (9, 3)
┌────────────┬───────────┬───────────┐
│ statistic  ┆ Revenue   ┆ COGS      │
│ ---        ┆ ---       ┆ ---       │
│ str        ┆ f64       ┆ f64       │
╞════════════╪═══════════╪═══════════╡
│ count      ┆ 3833.0    ┆ 3833.0    │
│ null_count ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 4.2866e6  ┆ 3.6951e6  │
│ std        ┆ 2.6248e6  ┆ 2.2198e6  │
│ min        ┆ 279813.94 ┆ 236576.31 │
│ 25%        ┆ 2.4711e6  ┆ 2.1506e6  │
│ 50%        ┆ 3647303.9 ┆ 3.1611e6  │
│ 75%        ┆ 5350877.2 ┆ 4.6373e6  │
│ max        ┆ 2.0905e7  ┆ 1.6536e7  │
└────────────┴───────────┴───────────┘

--- sample_submission ---

shape: (9, 3)
┌────────────┬───────────┬───────────┐
│ statistic  ┆ Revenue   ┆ COGS      │
│ ---        ┆ ---       ┆ ---       │
│ str        ┆ f64       ┆ f64       │
╞════════════╪═══════════╪═══════════╡
│ count      ┆ 548.0     ┆ 548.0     │
│ null_count ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 3.2498e6  ┆ 2.7838e6  │
│ std        ┆ 1.5817e6  ┆ 1.3603e6  │
│ min        ┆ 977332.85 ┆ 790258.95 │
│ 25%        ┆ 2033376.9 ┆ 1708216.3 │
│ 50%        ┆ 2.9798e6  ┆ 2.5775e6  │
│ 75%        ┆ 4.1814e6  ┆ 3.5156e6  │
│ max        ┆ 9.2834e6  ┆ 8.3415e6  │
└────────────┴───────────┴───────────┘

--- shipments ---

shape: (9, 3)
┌────────────┬───────────────┬──────────────┐
│ statistic  ┆ order_id      ┆ shipping_fee │
│ ---        ┆ ---           ┆ ---          │
│ str        ┆ f64           ┆ f64          │
╞════════════╪═══════════════╪══════════════╡
│ count      ┆ 566067.0      ┆ 566067.0     │
│ null_count ┆ 0.0           ┆ 0.0          │
│ mean       ┆ 415816.869664 ┆ 4.962857     │
│ std        ┆ 240007.311562 ┆ 8.887355     │
│ min        ┆ 1.0           ┆ 0.0          │
│ 25%        ┆ 208193.0      ┆ 0.87         │
│ 50%        ┆ 415866.0      ┆ 1.73         │
│ 75%        ┆ 623219.0      ┆ 2.6          │
│ max        ┆ 834325.0      ┆ 32.0         │
└────────────┴───────────────┴──────────────┘

--- web_traffic ---

shape: (9, 6)
┌────────────┬──────────────┬─────────────────┬───────────────┬─────────────┬──────────────────────┐
│ statistic  ┆ sessions     ┆ unique_visitors ┆ page_views    ┆ bounce_rate ┆ avg_session_duration │
│ ---        ┆ ---          ┆ ---             ┆ ---           ┆ ---         ┆ _sec                 │
│ str        ┆ f64          ┆ f64             ┆ f64           ┆ f64         ┆ ---                  │
│            ┆              ┆                 ┆               ┆             ┆ f64                  │
╞════════════╪══════════════╪═════════════════╪═══════════════╪═════════════╪══════════════════════╡
│ count      ┆ 3652.0       ┆ 3652.0          ┆ 3652.0        ┆ 3652.0      ┆ 3652.0               │
│ null_count ┆ 0.0          ┆ 0.0             ┆ 0.0           ┆ 0.0         ┆ 0.0                  │
│ mean       ┆ 25041.768072 ┆ 19031.404436    ┆ 108615.224535 ┆ 0.004487    ┆ 210.283242           │
│ std        ┆ 9422.609335  ┆ 7237.953062     ┆ 44472.055524  ┆ 0.000753    ┆ 63.771711            │
│ min        ┆ 7973.0       ┆ 6136.0          ┆ 30451.0       ┆ 0.0032      ┆ 100.1                │
│ 25%        ┆ 17101.0      ┆ 12915.0         ┆ 73001.0       ┆ 0.00385     ┆ 156.7                │
│ 50%        ┆ 23645.0      ┆ 17925.0         ┆ 101030.0      ┆ 0.00445     ┆ 209.3                │
│ 75%        ┆ 31779.0      ┆ 24191.0         ┆ 138084.0      ┆ 0.00516     ┆ 266.2                │
│ max        ┆ 50947.0      ┆ 40430.0         ┆ 275560.0      ┆ 0.0058      ┆ 319.9                │
└────────────┴──────────────┴─────────────────┴───────────────┴─────────────┴──────────────────────┘

## 5. Phát hiện Outlier (Outlier Detection)

In [ ]:
def check_outliers_iqr(df, col):
    s = df.get_column(col).drop_nulls()
    if len(s) == 0:
        return 0, 0, 0
    q1 = s.quantile(0.25)
    q3 = s.quantile(0.75)
    if q1 is None or q3 is None:
        return 0, 0, 0
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    
    outliers = df.filter((pl.col(col) < lower_bound) | (pl.col(col) > upper_bound))
    return len(outliers), lower_bound, upper_bound

for name, df in all_dfs.items():
    num_cols = [col for col, dtype in df.schema.items() if dtype in pl.NUMERIC_DTYPES]
    outlier_summary = []
    for col in num_cols:
        try:
            n_outliers, lb, ub = check_outliers_iqr(df, col)
            if n_outliers > 0:
                outlier_summary.append({
                    "Column": col,
                    "Outliers": n_outliers,
                    "%": round(n_outliers / len(df) * 100, 2)
                })
        except Exception as e:
            pass
    if outlier_summary:
        print(f"\n--- {name} Outliers ---")
        display(pl.DataFrame(outlier_summary).sort("Outliers", descending=True))

C:\Users\Admin\AppData\Local\Temp\ipykernel_26392\405703035.py:17: DeprecationWarning: `NUMERIC_DTYPES` was deprecated in version 1.0.0. Define your own data type groups or use the `polars.selectors` module for selecting columns of a certain data type.
  num_cols = [col for col, dtype in df.schema.items() if dtype in pl.NUMERIC_DTYPES]

--- inventory Outliers ---

shape: (8, 3)
┌───────────────────┬──────────┬───────┐
│ Column            ┆ Outliers ┆ %     │
│ ---               ┆ ---      ┆ ---   │
│ str               ┆ i64      ┆ f64   │
╞═══════════════════╪══════════╪═══════╡
│ overstock_flag    ┆ 14305    ┆ 23.74 │
│ days_of_supply    ┆ 7455     ┆ 12.37 │
│ stock_on_hand     ┆ 6432     ┆ 10.68 │
│ units_received    ┆ 6392     ┆ 10.61 │
│ units_sold        ┆ 6388     ┆ 10.6  │
│ sell_through_rate ┆ 1284     ┆ 2.13  │
│ stockout_days     ┆ 724      ┆ 1.2   │
│ fill_rate         ┆ 724      ┆ 1.2   │
└───────────────────┴──────────┴───────┘

--- order_items Outliers ---

shape: (2, 3)
┌─────────────────┬──────────┬──────┐
│ Column          ┆ Outliers ┆ %    │
│ ---             ┆ ---      ┆ ---  │
│ str             ┆ i64      ┆ f64  │
╞═════════════════╪══════════╪══════╡
│ discount_amount ┆ 105767   ┆ 14.8 │
│ unit_price      ┆ 8623     ┆ 1.21 │
└─────────────────┴──────────┴──────┘

--- payments Outliers ---

shape: (1, 3)
┌───────────────┬──────────┬──────┐
│ Column        ┆ Outliers ┆ %    │
│ ---           ┆ ---      ┆ ---  │
│ str           ┆ i64      ┆ f64  │
╞═══════════════╪══════════╪══════╡
│ payment_value ┆ 30219    ┆ 4.67 │
└───────────────┴──────────┴──────┘

--- products Outliers ---

shape: (2, 3)
┌────────┬──────────┬──────┐
│ Column ┆ Outliers ┆ %    │
│ ---    ┆ ---      ┆ ---  │
│ str    ┆ i64      ┆ f64  │
╞════════╪══════════╪══════╡
│ cogs   ┆ 37       ┆ 1.53 │
│ price  ┆ 31       ┆ 1.29 │
└────────┴──────────┴──────┘

--- promotions Outliers ---

shape: (2, 3)
┌────────────────┬──────────┬──────┐
│ Column         ┆ Outliers ┆ %    │
│ ---            ┆ ---      ┆ ---  │
│ str            ┆ i64      ┆ f64  │
╞════════════════╪══════════╪══════╡
│ stackable_flag ┆ 12       ┆ 24.0 │
│ discount_value ┆ 5        ┆ 10.0 │
└────────────────┴──────────┴──────┘

--- returns Outliers ---

shape: (1, 3)
┌───────────────┬──────────┬──────┐
│ Column        ┆ Outliers ┆ %    │
│ ---           ┆ ---      ┆ ---  │
│ str           ┆ i64      ┆ f64  │
╞═══════════════╪══════════╪══════╡
│ refund_amount ┆ 2778     ┆ 6.96 │
└───────────────┴──────────┴──────┘

--- sales Outliers ---

shape: (2, 3)
┌─────────┬──────────┬──────┐
│ Column  ┆ Outliers ┆ %    │
│ ---     ┆ ---      ┆ ---  │
│ str     ┆ i64      ┆ f64  │
╞═════════╪══════════╪══════╡
│ Revenue ┆ 169      ┆ 4.41 │
│ COGS    ┆ 165      ┆ 4.3  │
└─────────┴──────────┴──────┘

--- sample_submission Outliers ---

shape: (2, 3)
┌─────────┬──────────┬──────┐
│ Column  ┆ Outliers ┆ %    │
│ ---     ┆ ---      ┆ ---  │
│ str     ┆ i64      ┆ f64  │
╞═════════╪══════════╪══════╡
│ COGS    ┆ 18       ┆ 3.28 │
│ Revenue ┆ 16       ┆ 2.92 │
└─────────┴──────────┴──────┘

--- shipments Outliers ---

shape: (1, 3)
┌──────────────┬──────────┬───────┐
│ Column       ┆ Outliers ┆ %     │
│ ---          ┆ ---      ┆ ---   │
│ str          ┆ i64      ┆ f64   │
╞══════════════╪══════════╪═══════╡
│ shipping_fee ┆ 76050    ┆ 13.43 │
└──────────────┴──────────┴───────┘

--- web_traffic Outliers ---

shape: (1, 3)
┌────────────┬──────────┬──────┐
│ Column     ┆ Outliers ┆ %    │
│ ---        ┆ ---      ┆ ---  │
│ str        ┆ i64      ┆ f64  │
╞════════════╪══════════╪══════╡
│ page_views ┆ 18       ┆ 0.49 │
└────────────┴──────────┴──────┘